In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('insurance.csv')

In [4]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [10]:
df.shape

(1338, 7)

In [11]:
df = df.drop('region', 1)

In [12]:
df.shape

(1338, 6)

In [13]:
df.head()

age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [17]:
# doing label encoding in just 1 line
# female -> 0 and male -> 1
df['sex'] = df['sex'].astype('category').cat.codes

In [24]:
df['smoker'] = df['smoker'].astype('category').cat.codes

In [25]:
df.head()

age  sex     bmi  children  smoker      charges
0   19    0  27.900         0       1  16884.92400
1   18    1  33.770         1       0   1725.55230
2   28    1  33.000         3       0   4449.46200
3   33    1  22.705         0       0  21984.47061
4   32    1  28.880         0       0   3866.85520

In [28]:
input_col = ['age', 'sex', 'bmi', 'smoker']
X = df[input_col].values

In [29]:
y = df['charges'].values

In [30]:
X.shape

(1338, 4)

In [32]:
y = y.reshape(1338, 1)

In [33]:
y.shape

(1338, 1)

# Train test split

In [39]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [42]:
X_train.shape

(1070, 4)

In [43]:
X_test.shape

(268, 4)

# Model Building

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
# creating a linear reg model
model = LinearRegression()

In [46]:
# train this model
model.fit(X_train, y_train)

LinearRegression()

In [47]:
model.coef_

array([[  256.95069044,  -291.98622684,   316.32755992, 23622.89126052]])

In [48]:
model.intercept_

array([-11181.73889791])

# Predict

In [50]:
y_pred = model.predict(X_test)

In [51]:
y_pred[:5]

array([[ 3767.44881478],
       [ 2375.47664714],
       [12784.44754701],
       [28096.10549201],
       [ 1432.84282176]])

In [52]:
y_test[:5]

array([[ 2719.27975],
       [ 2007.945  ],
       [10928.849  ],
       [36189.1017 ],
       [ 2304.0022 ]])

# Score

In [53]:
model.score(X_test, y_test)

0.7900242336514673