In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [7]:
a = [45, 2, 5, 10, 9, 1, 11]

In [8]:
type(a)

list

In [10]:
arr = np.array(a)

In [11]:
arr

array([45,  2,  5, 10,  9,  1, 11])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.shape

(7,)

In [14]:
a + 1

TypeError: can only concatenate list (not "int") to list

In [15]:
arr + 1

array([46,  3,  6, 11, 10,  2, 12])

In [16]:
arr*2

array([90,  4, 10, 20, 18,  2, 22])

In [17]:
arr2 = np.array([1,2,3,4,5,6,7])

In [18]:
arr2

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
arr_add = arr + arr2

In [21]:
arr_add

array([46,  4,  8, 14, 14,  7, 18])

In [25]:
arr / arr2

array([45.        ,  1.        ,  1.66666667,  2.5       ,  1.8       ,
        0.16666667,  1.57142857])

In [26]:
arr_2d = np.array([[1,2,3], 
                   [4,5,6]])

In [27]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr_2d.shape

(2, 3)

In [56]:
r1 = np.random.randint(1, 10, size = (5,5) )
r2 = np.random.randint(1, 10, size = (5,4) )

In [57]:
r1

array([[1, 6, 1, 4, 9],
       [7, 4, 7, 4, 7],
       [3, 7, 8, 8, 9],
       [9, 4, 4, 7, 8],
       [9, 7, 4, 7, 8]])

In [58]:
r2

array([[3, 9, 4, 4],
       [8, 4, 8, 5],
       [5, 5, 7, 7],
       [9, 9, 7, 9],
       [4, 7, 8, 8]])

In [61]:
r1.shape

(5, 5)

In [60]:
r2.shape

(5, 4)

In [65]:
# matrix multiplication
ans = np.dot(r1, r2)

In [66]:
ans

array([[128, 137, 159, 149],
       [152, 199, 193, 189],
       [213, 230, 252, 247],
       [174, 236, 209, 211],
       [198, 248, 233, 226]])

In [67]:
r2

array([[3, 9, 4, 4],
       [8, 4, 8, 5],
       [5, 5, 7, 7],
       [9, 9, 7, 9],
       [4, 7, 8, 8]])

In [69]:
r2_t = np.transpose(r2)

In [70]:
r2_t

array([[3, 8, 5, 9, 4],
       [9, 4, 5, 9, 7],
       [4, 8, 7, 7, 8],
       [4, 5, 7, 9, 8]])

# Slicing

In [71]:
arr

array([45,  2,  5, 10,  9,  1, 11])

In [72]:
arr[0]

45

In [74]:
arr[ 1 : 4 ]

array([ 2,  5, 10])

In [75]:
arr[ : ]

array([45,  2,  5, 10,  9,  1, 11])

In [77]:
r1

array([[1, 6, 1, 4, 9],
       [7, 4, 7, 4, 7],
       [3, 7, 8, 8, 9],
       [9, 4, 4, 7, 8],
       [9, 7, 4, 7, 8]])

In [78]:
r1[ 1 : 3]

array([[7, 4, 7, 4, 7],
       [3, 7, 8, 8, 9]])

In [83]:
# slicing in 2d
r1[ 2:4 , 1: 4]

array([[7, 8, 8],
       [4, 4, 7]])

In [85]:
r1[1:5, 2:4]

array([[7, 4],
       [8, 8],
       [4, 7],
       [4, 7]])

In [86]:
data = "We are learning Python."

In [89]:
data[3:15]

'are learning'

# Misc.

In [91]:
np.sqrt(arr)

array([6.70820393, 1.41421356, 2.23606798, 3.16227766, 3.        ,
       1.        , 3.31662479])

In [94]:
np.round(np.sqrt(arr), decimals=1)

array([6.7, 1.4, 2.2, 3.2, 3. , 1. , 3.3])

In [95]:
np.log(1)

0.0

In [96]:
np.sin(0)

0.0

In [98]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Cheatsheet : https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf